name: Simple example of using

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Pierrot
        uses: ./
        with:
          version: 0.9.9
      - name: Print
        run: pierrot -version
