name: Simple example of using

on: [push]

jobs:
  check:
    name: 'Use Pierrot on ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Pierrot
        uses: ./
        with:
          version: 0.9.9
      - name: Print
        run: pierrot -version
